name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests --file pom.xml

      #- name: Run tests
      #  run: mvn test --file pom.xml

      # Optionally, you can add a step to publish your artifact or deploy it
      #- name: Upload artifact
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: spring-boot-app
      #    path: target/*.jar
